### ISSUE TITLE
The fuck?

### ISSUE THREAD

**Issue by Adnn** [ShredEagle/shred-project-helper#1]
![image](https://user-images.githubusercontent.com/3911163/186195701-c312c4d4-4a3c-4d44-87ad-83524ba075d2.png)

**Comment by FranzPoize** [comment]
L'avantage c'est que c'est uniquement une blague. Pas une bonne blague mais une blague et qu'il supprime pas le répertoire. Je réglerais ça demain.

**Comment by Adnn** [comment]
Hahaa, oui j'étais content après de voir qu'il était toujours intact !

Le mar. 23 août 2022, 17:43, Francois Poizat ***@***.***> a
écrit :

**Comment by FranzPoize** [comment]
fix by bccc445
